#!/bin/bash
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/SingleMuon_Run2017B_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/SingleMuon_Run2017C_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/SingleMuon_Run2017C_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/SingleMuon_Run2017D_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/SingleMuon_Run2017E_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/SingleMuon_Run2017E_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/SingleMuon_Run2017F_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/SingleMuon_Run2017F_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/DYJetsToLL_M-10to50_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/DYJetsToLL_M-10to50_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/DYJetsToLL_M-50_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/DYJetsToLL_M-50_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/DYJetsToLL_M-50_2.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/DYJetsToLL_M-50_3.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/WJetsToLNu_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/WJetsToLNu_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/TTTo2L2Nu_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/TTTo2L2Nu_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/TTTo2L2Nu_2.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/TTTo2L2Nu_3.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/TTToSemiLeptonic_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/TTToSemiLeptonic_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/TTToSemiLeptonic_2.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/TTToSemiLeptonic_3.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/WWTo2L2Nu_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/WWTo2L2Nu_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/WZTo2Q2L_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/WZTo2Q2L_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/WZTo3LNu_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/WZTo3LNu_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ZZTo2L2Nu_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ZZTo2L2Nu_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ZZTo2Q2L_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ZZTo2Q2L_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ST_t-channel_top_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ST_t-channel_top_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ST_t-channel_antitop_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ST_t-channel_antitop_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ST_tW_top_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ST_tW_top_1.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ST_tW_antitop_0.submit
condor_submit /afs/cern.ch/user/s/svashish/MuTauFR/condor/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/ST_tW_antitop_1.submit
rm /afs/cern.ch/user/s/svashish/MuTauFR/selection/mutau_UL2017_LooseVsJet_TightVsMu_TightVsE/*.root
